networks:
  n8n_net:
    driver: bridge
  nginx-proxy:
    external: true

services:
  mongodb-atlas:
    image: mongodb/mongodb-atlas-local 
    restart: unless-stopped
    container_name: mongodb-atlas
    user: root
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - /home/ai/mongo-atlas/data:/data/db 
      - /home/ai/mongo-atlas/config:/data/configdb    
    ports:
     - 27017:27017
    networks:
      - n8n_net
  n8n:
    image: rxchi1d/n8n-ffmpeg
    restart: unless-stopped
    container_name: n8n
    depends_on:
      - mongodb-atlas
      - pproxy
    environment:
      # - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - NODE_ENV=production
      - HTTP_PROXY=http://pproxy
      - HTTPS_PROXY=http://pproxy
      - LANGCHAIN_ENDPOINT="https://api.smith.langchain.com"
      - LANGCHAIN_TRACING_V2=true
      - LANGCHAIN_API_KEY="${LANGCHAIN_API_KEY}"
      - GENERIC_TIMEZONE="${GENERIC_TIMEZONE}"
      - WEBHOOK_URL="${WEBHOOK_URL}"
      - N8N_EDITOR_BASE_URL="${N8N_EDITOR_BASE_URL}"
      - N8N_PERSONALIZATION_ENABLED=false
    volumes:
      - /home/ai/n8n/data:/home/node/.n8n:rw
      - /home/ai/n8n/files:/files
    networks:
      - n8n_net
      - nginx-proxy
### Proxy ###
  pproxy:
    image: mosajjal/pproxy
    container_name: pproxy
    restart: unless-stopped
    command: -l http://:80 -vv -r socks5://${PROXY_HOST}:${PROXY_PORT}?rules#${PROXY_USER}:${PROXY_PASSWORD}
    tty: true
    # healthcheck:
    #     test: netstat -an | grep -q 8[0]
    #     interval: 1m30s
    #     timeout: 10s
    #     retries: 3
    #     start_period: 10s
    #     start_interval: 5s
    volumes:
      - /home/pproxy/proxy_rules:/rules
    networks:
      - n8n_net

  subtitle_api:
    image: silvar/subtitle_api:latest
    container_name: subtitle_api
    restart: unless-stopped
    networks:
      - n8n_net
  
